version: '3.9'

services:
  helix:
    container_name: helix-alpha
    image: registry.helix-dev.synadia.io/helix:tag-rc
    hostname: helix
    command: server start
    volumes:
      - ./nats/nsc/keys:/etc/nsc/keys
      - ./rna.cue:/app/rna.cue
      - helix-data:/app/data
    ports:
      - 8080:8080
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  nats-bootstrap:
    container_name: nats-bootstrap
    image: natsio/nats-box:latest
    command: /setup/bootstrap.sh -s
    volumes:
      - ./:/setup

  nats-a:
    container_name: helix-alpha-nats-a
    image: nats:2.9.9-alpine
    hostname: nats
    volumes:
      - ./nats/nats-a/nats-server.conf:/etc/nats/nats-server.conf
      - nats-a:/data
    ports:
      - 4222:4222
    depends_on:
      nats-bootstrap:
        condition: service_completed_successfully

  nats-b:
    container_name: helix-alpha-nats-b
    image: nats:2.9.9-alpine
    hostname: nats
    volumes:
      - ./nats/nats-b/nats-server.conf:/etc/nats/nats-server.conf
      - nats-b:/data
    ports:
      - 4223:4222
    depends_on:
      nats-bootstrap:
        condition: service_completed_successfully

  nats-c:
    container_name: helix-alpha-nats-c
    image: nats:2.9.9-alpine
    hostname: nats
    volumes:
      - ./nats/nats-c/nats-server.conf:/etc/nats/nats-server.conf
      - nats-c:/data
    ports:
      - 4224:4222
    depends_on:
      nats-bootstrap:
        condition: service_completed_successfully

volumes:
  nats-a: {}
  nats-b: {}
  nats-c: {}
  helix-data: {}
