version: '3.9'

services:
  helix:
    container_name: helix
    image: registry.helix-dev.synadia.io/helix:v0.0.1-rc.5
    hostname: helix
    command: ["-c", "/conf/helix/helix.json", "server", "start"]
    volumes:
      - ./conf:/conf
      - helix-data:/app/data
    ports:
      - 8080:8080

volumes:
  helix-data: {}
