version: '3.9'

services:
  control-plane:
    container_name: control-plane
    image: registry.synadia.io/control-plane:latest
    hostname: control-plane
    command: ["-c", "/etc/syn-cp/syn-cp.json", "server", "start"]
    volumes:
      - ./conf/syn-cp:/etc/syn-cp
      - control-plane-data:/app/data
    ports:
      - 8080:8080
      - 8443:8443

volumes:
  control-plane-data: {}
