version: '3.9'

services:
  control-plane:
    container_name: control-plane
    image: registry.synadia.io/control-plane
    hostname: control-plane
    command: ['server', 'start']
    volumes:
      - ./syn-cp.yaml:/app/syn-cp.yaml
      - control-plane-data:/app/data
    ports:
      - 8080:8080

  nats-a:
    container_name: control-plane-nats-a
    image: registry.synadia.io/synadia-server
    hostname: nats
    environment:
      SYNADIA_SERVER_URL: http://control-plane:8080
      SYNADIA_SERVER_CP_NATS_URL: ws://control-plane:8080/api/cp-nats
    command: ["--opts-file", "/conf/opts.yaml", "--config", "/conf/nats.conf"]
    volumes:
      - ./conf/nats-a:/conf
      - nats-a:/app/data
    ports:
      - 4222:4222

  nats-b:
    container_name: control-plane-nats-b
    image: registry.synadia.io/synadia-server
    hostname: nats
    environment:
      SYNADIA_SERVER_URL: http://control-plane:8080
      SYNADIA_SERVER_CP_NATS_URL: ws://control-plane:8080/api/cp-nats
    command: ["--opts-file", "/conf/opts.yaml", "--config", "/conf/nats.conf"]
    volumes:
      - ./conf/nats-b:/conf
      - nats-b:/app/data
    ports:
      - 4223:4222
  
  nats-c:
    container_name: control-plane-nats-c
    image: registry.synadia.io/synadia-server
    hostname: nats
    environment:
      SYNADIA_SERVER_URL: http://control-plane:8080
      SYNADIA_SERVER_CP_NATS_URL: ws://control-plane:8080/api/cp-nats
    command: ["--opts-file", "/conf/opts.yaml", "--config", "/conf/nats.conf"]
    volumes:
      - ./conf/nats-c:/conf
      - nats-c:/app/data
    ports:
      - 4224:4222

volumes:
  nats-a: {}
  nats-b: {}
  nats-c: {}
  control-plane-data: {}
